# CS 349 HW 2 Pitfalls

Below are some functions that may be useful for several parts in homework 2.

In [1]:
import numpy as np

## distances.py

Below are several numpy functions that may be useful when writing code for the distance metrics.

**np.sqrt** calculates the square root of a single number or each value in an array

In [2]:
np.sqrt([1, 4, 9, 16])

array([1., 2., 3., 4.])

**np.sum** adds up all values within an array

In [3]:
np.sum([-1, 2, 3]), np.sum([4, 5, 6])

(4, 15)

**np.dot** computes the dot product of two arrays

In [4]:
np.dot([-1, 2, 3], [4, 5, 6])

24

**np.square** calculates the square of a single number or each number in an array

In [5]:
np.square([-1, 2, 3])

array([1, 4, 9])

**np.abs** computes the absolute value of a single number or each number in an array

In [6]:
x = np.array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])
np.abs(x)

array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])

## k_nearest_neighbor.py

**np.mean** is used to compute the mean of an array. **np.median** finds the median in an array. **np.unique** keeps only unique values of an array and can be set to return the count for each unique value (you can use this for computing the **mode**).

In [7]:
x = [-1, 2, 1, 3, 3]

In [8]:
np.mean(x)

1.6

In [9]:
np.median(x)

2.0

In [10]:
np.unique(x, return_counts=True)

(array([-1,  1,  2,  3]), array([1, 1, 1, 2]))

In [11]:
print(np.sort(x, axis=0))     # sorts array
print(np.argsort(x, axis=0))  # returns idices of sorted array  

[-1  1  2  3  3]
[0 2 1 3 4]


## collaborative_filtering.py

**np.argwhere** is used to find the indices of the values where a condition holds true.

In [12]:
x = np.array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])
print(np.argwhere(x == 1))

[[0]
 [9]]
