# NumPy Primer for COMP_SCI 349

In CS 349, you will use NumPy in every assignment. NumPy is a Python library for multidimensional matrix manipulation and linear algebra. It adds functionalities similar to MATLAB and Octave to Python.

We don't want NumPy to add an unnecessary layer of complexity to this course, so this optional notebook lets you get your feet wet with the library before diving into assignments. You'll learn about the fundamental constructs within NumPy and it'll introduce you to the key functions you'll end up using throughout the course. We're assuming you're familiar with Python (or you can pick it up quickly) but have never used NumPy before. As you go through this guide, play around with each function and try to do things on your own!

As you complete your assignments, this guide can serve as a reference. However, your primary reference should always be the [official NumPy reference](https://docs.scipy.org/doc/numpy/reference/index.html). Furthermore, Google is always your friend when you're debugging an error you've never seen before. Lastly, this notebook draws a bit from the [NumPy basics guide](https://numpy.org/devdocs/user/absolute_beginners.html), so feel free to check that out.

In [1]:
import numpy as np  # np is usually the alias used when importing numpy

NumPy arrays are of the class `ndarray` (n dimensional array). There are many ways to create arrays depending on your needs.

The most basic way to create an array is using the function `np.array()`.

In [2]:
x = np.array([1, 2, 3, 4, 5, 6])  # creates 1D array called a vector

y = np.array([[2, 4, 6], # creates a 2D array
             [-2, -4, -6]])

z = np.array([[[2, 5, 7], # creates a 3D array
               [3, 9, 1]],
              
              [[9, 8, 7],
               [3, 2, 2]]])

In [4]:
print("x =\n", x, '\n')
print("y =\n", y, '\n')
print("z =\n", z)

x =
 [1 2 3 4 5 6] 

y =
 [[ 2  4  6]
 [-2 -4 -6]] 

z =
 [[[2 5 7]
  [3 9 1]]

 [[9 8 7]
  [3 2 2]]]


For the most part, you shouldn't need anything beyond 3D arrays.

To get the dimensions of an array, use `ndarray.shape` or `np.shape()`.

In [5]:
print(x.shape)
print(np.shape(x))

(6,)
(6,)


Notice how a 1D array, or vector, isn't of shape (3, 1) or (1, 3). This is because NumPy interprets them as both shapes, allowing you to calculate dot products and add vectors together without worrying about their second dimension. In other words, the 1 is implicit. 

In [6]:
print(y.shape)
print(z.shape)

(2, 3)
(2, 2, 3)


Just as we can get the shape of an array, we can also change the shape of an array using `ndarray.reshape()` or `np.reshape()`.

In [7]:
print(x.reshape(3,2))
print('\n')
print(x.reshape(2, 3, 1))

[[1 2]
 [3 4]
 [5 6]]


[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


### Row major indexing

NumPy uses [row-major indexing](https://en.wikipedia.org/wiki/Row-_and_column-major_order) by default, which means that indexes go left to right across the columns. An array with a shape of (2,3) means that there are 2 row and 3 columns. A 3D array with a shape of (2, 2, 3) means that there are 2 arrays stacked, each with 2 rows and 3 columns. When indexing an array, the first number is the row number and the second number is the column number. Both start from zero.

In [8]:
# 1D array
print(x)
print(x[0])
print(x[-1], '\n')  # arrays can be indexed backwards as well

# 2D array
print(y)
print(y[0, 2])
print(y[:,0])  # entire 0th col; ':' means everything in that row/col
print(y[1,:], '\n')  # entire 1st row

# 3D array 
print("z =", z, '\n')
print(z[0])  # first layer of the stacked arrays
print(z[0, 0, :])  # first row of the first layer

[1 2 3 4 5 6]
1
6 

[[ 2  4  6]
 [-2 -4 -6]]
6
[ 2 -2]
[-2 -4 -6] 

z = [[[2 5 7]
  [3 9 1]]

 [[9 8 7]
  [3 2 2]]] 

[[2 5 7]
 [3 9 1]]
[2 5 7]


### Array slices

When training a machine learner on a dataset, we often split the dataset into a training set and a testing set. If the dataset is stored as a NumPy array, we can slice the array to get a training set and a testing set. Slicing an array means cutting out a part of the array. The syntax for slicing an array is the same as how we index an array. When slicing, the `:` is used as follows: `start:stop:step`. None of these are mandatory parameters and when they're not specified, they default to `start=0`, `stop=size of dimension`, `step=1`. Therefore, when just a colon is present, that entire dimension is grabbed.

In [9]:
print("x =",x, '\n')
print(x[0:2], '\n')  # notice how the 2nd number isn't printed

print("y =", y, '\n')
print(y[:,0], '\n')  # all of the rows and only the 1st col
print(y[:2:, :2:], '\n')  # first two rows and first two cols (equal to y[0:2, 0:2], y[0:2:0, 0:2:0], and y[0:2:, 0:2:])

x = [1 2 3 4 5 6] 

[1 2] 

y = [[ 2  4  6]
 [-2 -4 -6]] 

[ 2 -2] 

[[ 2  4]
 [-2 -4]] 



In [10]:
# Here's some space to play around with the slicing of 3D arrays

**NOTE:** Array indexing/slicing does **not** create a copy of the array. If you modify the slice or index, then the underlying data structure will also be modified.

[Visual representation for indexing and slicing.](https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/)

## NumPy axes

Axes are how the rows and columns are referred to. In NumPy, `axis=0` refers to the rows. That is, specifying `axis=0` means we want to go down the rows. Similarily, `axis=1` specifies that we want to go across the columns. Going through some examples should clear this up.

The function `np.concatenate()` allows us to concatenate two or more arrays together *along a given axis*. 

In [11]:
a1 = np.array([[1, 2],
               [3, 4]])

a2 = np.array([[9, 8], 
               [7, 6]])

np.concatenate([a1, a2], axis=0)  # pass in the arrays to concatenate as a sequence (tuple or array would work)

array([[1, 2],
       [3, 4],
       [9, 8],
       [7, 6]])

Because `axis=0` is specified, `np.concatenate()` will append `a2` to the rows of `a1`. We're telling `np.concatenate()` to join the two arrays along axis 0. Similarly, let's see what happens when we specify `axis=1`.


In [12]:
np.concatenate([a1, a2], axis=1)

array([[1, 2, 9, 8],
       [3, 4, 7, 6]])

**Challenge:** Extend the rows of `a1` by concatenating `a3` to it. Then, extend `a1` by concatenating `a4` to it. In both cases, you'll need to use `reshape` and `concatenate`.

In [13]:
a3 = np.array([5, 6, 7, 8])
a4 = np.array([10, 10])

In [14]:
### ANSWERS ###

np.concatenate([a1, a3.reshape(2,2)], axis=0)
np.concatenate([a1, a4.reshape(1,2)], axis=0)

array([[ 1,  2],
       [ 3,  4],
       [10, 10]])

## More ways to create arrays

### np.arange([start, ]stop, [step, ]dtype=None)

Generate an array with evenly spaced values within an interval \[start, stop).

**start (optional):** Default value of 0.  
**stop:** Interval doesn't include the stop.  
**step (optional):** Default value of 1. Define spacing between individual elements in array

In [15]:
print(np.arange(5))

[0 1 2 3 4]


In [16]:
print(np.arange(1, 10))

[1 2 3 4 5 6 7 8 9]


In [17]:
# 5 becomes the optional start parameter, so this arange returns empty
print(np.arange(5, 2))

[]


In [18]:
print(np.arange(5, 10, 0.5))

[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


### np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

Generate an array with a precise number of evenly spaced values over a given interval. Unlike `np.arange()`, `np.linspace` let's you directly control the exact size of the array.

**start:** mandatory  
**end:** mandatory  
**num (optional):** Default value of 50. Defines the number of elements within the generated sequence.  

Rest of api can be found in documentation.

In [19]:
print(np.linspace(0, 5))

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [20]:
print(np.linspace(5, 10, 3))

[ 5.   7.5 10. ]


### numpy.zeros(shape, dtype=float, order='C') 

Generate an array of all zeros with a certain shape.

**shape:** Tuple representing shape or single int; if int, then output is vector  
**dtype (optional):** Data type for the array; [can be many different types](https://docs.scipy.org/doc/numpy/user/basics.types.html); default is `float64`  
**order (optional):** C (row-major) or FORTRAN (column-major) ordering of data. Shouldn't need to mess with this

In [21]:
print(np.zeros((2,3)))
print(np.zeros(4, dtype=np.int))
print(np.zeros((3,2), dtype=np.complex64))

[[0. 0. 0.]
 [0. 0. 0.]]
[0 0 0 0]
[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]


### numpy.zeros(shape, dtype=float, order='C') 

Generate an array of all ones with a certain shape.

In [22]:
print(np.ones((1,2)))

[[1. 1.]]


### numpy.eye(n, dtype=float) 

Generate the identity matrix (square matrix with 1 on the entire main diagonal)

**n:** Length of row and column

In [23]:
print(np.eye(1))
print(np.eye(7))

[[1.]]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


 ### numpy.random.randint(low, high=None, size=None, dtype='l')
 
Pulls number from a uniform distribution to generate a number or an array filled with random integers in a range.

**low:** If only this parameter is provided, this becomes the high.
**high (optional):** One above the largest possible integer.
**size (optional):** If `size=None`, then returns a single number. Else `size` must be an int or a tuple.

In [24]:
print(np.random.randint(2))
print(np.random.randint(5, 9,size=(2,4)))

1
[[7 6 5 5]
 [5 7 6 8]]


### numpy.random.uniform(low=0.0, high=1.0, size=None)

Pull floats from the uniform distribution to generate a number or an array.

**low (optional):** All values will be greater than or equal to `low`.  
**high (optional):** All values will be less than `high`.

In [25]:
print(np.random.uniform())
print(np.random.uniform(0.4, 3, size=(2,2)))

0.7931911463143781
[[0.57754128 0.61199507]
 [1.69198612 0.4932295 ]]


### numpy.random.normal(loc=0.0, scale=1.0, size=None)

Pulls floats from a normal distribution.

**loc (optional):** Center/mean of distribution.
**scale (optional):** Standard deviation of distribution.

In [26]:
print(np.random.normal(3, 1.5))
print(np.random.normal(3, 2, size=(2,2)))

3.1783815868822085
[[2.72398579 0.7122572 ]
 [2.85864198 5.99070434]]


## Extending and shrinking existing arrays 

### numpy.insert(arr, obj, values, axis=None)

Insert values along the specified axis of `arr` before the given indices in `obj`.  
**arr:** Array to extend.  
**obj:** The indices at where to insert values. This can be a sequence of numbers.  
**values:** What to insert. If `values` is of a different type than the data in `arr`, `values` is cast to the type in `arr`. Make sure the shape of `values` is valid with respect to the shape of `arr`. This can be a sequence of numbers.  
**axis (optional):** If axis isn't specified, the array is flattened (made 1D).

In [27]:
print(x)
print(np.insert(x, 2, 9), '\n')
print(y)
print(np.insert(y, 5, 9))  # Insert 9 at index 5
print(np.insert(y, [2, 3], [9, 10]))   # Insert 9 at 2 and 1 at 3
print(np.insert(y, 1, 9, axis=1))  # Insert 9s into column (axis=1) at index 1
print(np.insert(y, 1, 9, axis=0))

[1 2 3 4 5 6]
[1 2 9 3 4 5 6] 

[[ 2  4  6]
 [-2 -4 -6]]
[ 2  4  6 -2 -4  9 -6]
[ 2  4  9  6 10 -2 -4 -6]
[[ 2  9  4  6]
 [-2  9 -4 -6]]
[[ 2  4  6]
 [ 9  9  9]
 [-2 -4 -6]]


### numpy.delete(arr, obj, axis=None)

Return a new array with the sub-arrays along an axis deleted.  
**arr:** Original array.  
**obj:** The subarrays to remove.  
**axis:** Axis along which to delete the subarray. If `None`, then the result is flattened, then returned.

In [28]:
arr = np.arange(1, 13, 1).reshape((3,4))
print("arr =", arr, '\n')

# delete first column and flatten output
print(np.delete(arr, 1),'\n')

# delete first row but keep 2D
print(np.delete(arr, 1, axis=0), '\n')

# remove every other column (axis=1 means columns and ::2 means start to finish and step size of 2)
print(np.delete(arr, np.s_[::2], axis=1))

arr = [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[ 1  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2  3  4]
 [ 9 10 11 12]] 

[[ 2  4]
 [ 6  8]
 [10 12]]


### np.append(arr, values, axis=None)

Append values to the end of an array. Modifies and returns a copy of the original array.

**arr:** Array to append to.  
**values:** Values to append must be of the correct shape.  
**axis: (optional)** Append along this axis. If it's not specified, then `arr` and `values` are both flattened before appending.

In [29]:
arr2 = np.arange(9, 18, 1).reshape((3,3))
print("arr2 =", arr2, '\n')
print(np.append(arr, arr2), '\n')
print(np.append(arr, arr2, axis=1))

arr2 = [[ 9 10 11]
 [12 13 14]
 [15 16 17]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12  9 10 11 12 13 14 15 16 17] 

[[ 1  2  3  4  9 10 11]
 [ 5  6  7  8 12 13 14]
 [ 9 10 11 12 15 16 17]]


### numpy.repeat(a, repeats, axis=None)

Repeat the elements of an array

**a:** Number or array to repeat.  
**repeats:** Number of times to repeat `a`.  
**axis (optional):** Axis along which to repeat. If not specified, then input and output are flattened.

In [30]:
print(np.repeat(10, 4), '\n')
print(np.repeat(arr2, 2, axis=1), '\n')
print(np.repeat(arr2, 2, axis=0))

[10 10 10 10] 

[[ 9  9 10 10 11 11]
 [12 12 13 13 14 14]
 [15 15 16 16 17 17]] 

[[ 9 10 11]
 [ 9 10 11]
 [12 13 14]
 [12 13 14]
 [15 16 17]
 [15 16 17]]


## Math Operations
### np.sum() vs "+"

#### Adds 5 to each element of the array

In [31]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [32]:
x + 5

array([5, 6, 7, 8, 9])

#### Sums across the elements of the array

In [33]:
np.sum(x)

10

#### Sums the elements across each column (axis = 0)

In [34]:
y = np.array([[1, 5, 2], [2, 1, 5]])
y

array([[1, 5, 2],
       [2, 1, 5]])

In [35]:
y.shape

(2, 3)

In [36]:
np.sum(y, axis = 0)

array([3, 6, 7])

#### Sums the elements across each row (axis = 1)

In [37]:
np.sum(y, axis = 1) #summing the elements in each row

array([8, 8])

In [38]:
z = np.array([[6, 1, 4], [3, 5, 5]])
z

array([[6, 1, 4],
       [3, 5, 5]])

#### Summing 2 arrays.

In [39]:
y + z

array([[ 7,  6,  6],
       [ 5,  6, 10]])

### np.subtract() vs "-"

#### Not the same as np.sum() vs "+", Cannot do subtraction across rows or columns

In [40]:
y - z

array([[-5,  4, -2],
       [-1, -4,  0]])

In [41]:
np.subtract(y, z)

array([[-5,  4, -2],
       [-1, -4,  0]])

In [42]:
np.subtract(y, axis=0)

ValueError: invalid number of arguments

### np.abs() or np.absolute(); both are the same

#### Find absolute value element wise.

In [43]:
x = np.array([[1, -4, 2], [-42, 21, 1]])
x

array([[  1,  -4,   2],
       [-42,  21,   1]])

In [44]:
np.abs(x)

array([[ 1,  4,  2],
       [42, 21,  1]])

### np.linalg.inv()

#### Explanation of matrix inverse: https://mathworld.wolfram.com/MatrixInverse.html

In [45]:
x = np.array([[1, -4, 2], [-42, 21, 1], [6,71, 55]])
x

array([[  1,  -4,   2],
       [-42,  21,   1],
       [  6,  71,  55]])

In [46]:
np.linalg.inv(x)

array([[-0.07529869, -0.02514587,  0.00319533],
       [-0.16087802, -0.00298694,  0.00590442],
       [ 0.2158933 ,  0.00659906,  0.01021117]])

### np.log2(), simple log base 2

In [47]:
x = np.array([[32, 25, 64], [2, 8, 10]])
x

array([[32, 25, 64],
       [ 2,  8, 10]])

#### Applies log base 2 element wise

In [48]:
np.log2(x)

array([[5.        , 4.64385619, 6.        ],
       [1.        , 3.        , 3.32192809]])

### np.power()

In [49]:
x = np.array([1, 4, 3, 5])
x

array([1, 4, 3, 5])

#### Applies power to each element.

In [50]:
np.power(x, 3)

array([  1,  64,  27, 125])

#### Applies each power element wise. The shapes of the powers and inputs must be the same

In [51]:
powers = np.array([2, 3, 1, 2])
np.power(x, powers)

array([ 1, 64,  3, 25])

## np.square() Same idea above.

In [52]:
np.square(x)

array([ 1, 16,  9, 25])

## np.var()

#### Calculates variance across whole array/matrix or across specified axis

In [53]:
x = np.array([1, 4, 3, 5])
x

array([1, 4, 3, 5])

In [54]:
np.var(x)

2.1875

In [55]:
y = np.array([[2, 6, 4], [3, 7, 5]])
y

array([[2, 6, 4],
       [3, 7, 5]])

In [56]:
np.var(y)

2.9166666666666665

In [57]:
np.var(y, axis = 0)

array([0.25, 0.25, 0.25])

In [58]:
np.var(y, axis = 1)

array([2.66666667, 2.66666667])

## np.std()

#### Standard deviation, same idea as above.

In [59]:
y

array([[2, 6, 4],
       [3, 7, 5]])

In [60]:
np.std(y)

1.707825127659933

In [61]:
np.std(y, axis = 0)

array([0.5, 0.5, 0.5])

In [62]:
np.std(y, axis = 1)

array([1.63299316, 1.63299316])

## np.mean()

####  Mean, same idea as above.

In [63]:
y

array([[2, 6, 4],
       [3, 7, 5]])

In [64]:
np.mean(y)

4.5

In [65]:
np.mean(y, axis = 0)

array([2.5, 6.5, 4.5])

In [66]:
np.mean(y, axis = 1)

array([4., 5.])

## np.floor()

#### Rounds down to nearest integer.

In [67]:
x = np.array([[2.3, 4.5, 3.93], [3, -1.7, 0.3]])
x

array([[ 2.3 ,  4.5 ,  3.93],
       [ 3.  , -1.7 ,  0.3 ]])

In [68]:
np.floor(3.5)

3.0

#### Applies floor element wise.

# Other operations

## np.sort() https://docs.scipy.org/doc/numpy/reference/generated/numpy.floor.html

In [69]:
x

array([[ 2.3 ,  4.5 ,  3.93],
       [ 3.  , -1.7 ,  0.3 ]])

In [70]:
np.sort(x)

array([[ 2.3 ,  3.93,  4.5 ],
       [-1.7 ,  0.3 ,  3.  ]])

In [71]:
np.sort(x, axis = 0)

array([[ 2.3 , -1.7 ,  0.3 ],
       [ 3.  ,  4.5 ,  3.93]])

#### axis = None flattens the array

In [72]:
np.sort(x, axis = None)

array([-1.7 ,  0.3 ,  2.3 ,  3.  ,  3.93,  4.5 ])

## np.argsort() https://docs.scipy.org/doc/numpy/reference/generated/numpy.argsort.html

#### like np.sort() but returns indices in sorted order

In [73]:
x

array([[ 2.3 ,  4.5 ,  3.93],
       [ 3.  , -1.7 ,  0.3 ]])

In [74]:
np.argsort(x)

array([[0, 2, 1],
       [1, 2, 0]])

In [75]:
np.argsort(x, axis = 0)

array([[0, 1, 1],
       [1, 0, 0]])

In [76]:
np.argsort(x, axis = None)

array([4, 5, 0, 3, 2, 1])

## np.allclose() https://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html

#### Returns True if two arrays are element-wise equal within a tolerance.

In [77]:
x = np.array([1, 6, 5])

In [78]:
y = np.array([1.7, 5.4, 5.1])

In [79]:
z = np.array([0.1, 5.5, 4.5])

In [80]:
np.allclose(x, y, 1)

True

In [81]:
np.allclose(x, z, 1)

False

## np.where() https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html

#### format: np.where(if, then, else)

In [82]:
x = np.array([[1, 5, 2], [4, 16, 3]])
x

array([[ 1,  5,  2],
       [ 4, 16,  3]])

In [83]:
np.where(x > 4, x, x + 2) #If the element is greater than 4, return that element, otherwise add 2 then return it

array([[ 3,  5,  4],
       [ 6, 16,  5]])

## np.argwhere() https://docs.scipy.org/doc/numpy/reference/generated/numpy.argwhere.html

In [84]:
x

array([[ 1,  5,  2],
       [ 4, 16,  3]])

In [85]:
np.argwhere(x > 4)

array([[0, 1],
       [1, 1]])

## np.maximum() https://docs.scipy.org/doc/numpy/reference/generated/numpy.maximum.html

In [86]:
x

array([[ 1,  5,  2],
       [ 4, 16,  3]])

In [87]:
y = np.array([[6, 4, 3], [7, 3, 12]])

In [88]:
np.maximum(x,y)

array([[ 6,  5,  3],
       [ 7, 16, 12]])

## np.max() or np.amax()

In [89]:
x

array([[ 1,  5,  2],
       [ 4, 16,  3]])

In [90]:
np.amax(x)

16

In [91]:
np.amax(x, axis = 0)

array([ 4, 16,  3])

In [92]:
np.amax(x, axis=1)

array([ 5, 16])

## np.argmax() https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html

In [93]:
y

array([[ 6,  4,  3],
       [ 7,  3, 12]])

In [94]:
np.argmax(y)

5

In [95]:
np.argmax(y, axis = 1)

array([0, 2])

In [96]:
np.argmax(y, axis = 0)

array([1, 0, 1])

## np.any() https://docs.scipy.org/doc/numpy/reference/generated/numpy.any.html

In [97]:
np.any([[True, False], [True, True]])

True

In [98]:
np.any([[False, False], [False, False]])

False

In [99]:
np.any([0, 2, 1, 0, 3])

True

In [100]:
np.any([0, 0, 0])

False

## np.all() https://docs.scipy.org/doc/numpy/reference/generated/numpy.all.html

In [101]:
np.all([[True, False], [True, True]])

False

In [102]:
np.any([[False, False], [False, False]])

False

In [103]:
np.all([[True, True], [True, True]])

True

In [104]:
np.all([1, 1, 1, 1])

True

In [105]:
np.all([1, 1, 1, 0])

False

## np.unique() https://docs.scipy.org/doc/numpy/reference/generated/numpy.unique.html

In [106]:
x = np.array([[2, 1, 6, 1, 6], [1, 1, 5, 1, 5]])
x

array([[2, 1, 6, 1, 6],
       [1, 1, 5, 1, 5]])

In [107]:
np.unique(x)

array([1, 2, 5, 6])

#### With axis parameter, returns unique rows/columns.

In [108]:
np.unique(x, axis=1)

array([[1, 2, 6],
       [1, 1, 5]])

In [109]:
np.unique(x, axis=0)

array([[1, 1, 5, 1, 5],
       [2, 1, 6, 1, 6]])

## np.sign() https://docs.scipy.org/doc/numpy/reference/generated/numpy.sign.html

In [110]:
x = np.array([[2, -4, 1, -2.5, 21], [3, -61, 2, 4, 21]])
x

array([[  2. ,  -4. ,   1. ,  -2.5,  21. ],
       [  3. , -61. ,   2. ,   4. ,  21. ]])

In [111]:
np.sign(x)

array([[ 1., -1.,  1., -1.,  1.],
       [ 1., -1.,  1.,  1.,  1.]])

In [112]:
np.floor(x)

array([[  2.,  -4.,   1.,  -3.,  21.],
       [  3., -61.,   2.,   4.,  21.]])